version: '3.9'

services:
  # Main Application
  app:
    build: .
    restart: unless-stopped
    ports:
      - "5500:5500"
    depends_on:
      db:
        condition: service_healthy

  # Nginx proxy
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d/temp.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/marketingcompany.tech/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/marketingcompany.tech/privkey.pem:/etc/nginx/ssl/privkey.pem
      # Database
  db:
    image: 'postgres:16.1-alpine3.18'
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      interval: 2s
      timeout: 5s
      retries: 3
      test: [ "CMD-SHELL", "pg_isready" ]
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '#SocialSync@2023'
      POSTGRES_DB: 'socialsync'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
